INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   37220964911,   '2011061515145211902',   'tarun',   'pp_reporting_tables',   'ta_nps_sample_2011',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using SLR_ID (varchar( 25 )) insert into unica_temp.UACEX1_152432_s3a(SLR_ID) values ( :SLR_ID );
Select		top 1000 bcn.acc_lang, bcn.src_ip, bcn.ux_time, 		(Case			When	tls_i0<tls_i1 	And	tls_i0<tls_i2 Then (tls_i0-tcp_min)*1000 			When	tls_i1<tls_i2 	And	tls_i1<tls_i0 Then (tls_i1-tcp_min)*1000 			Else	(tls_i2-tcp_min)*1000 end) As lat From	    pp_risk_model_views.dw_ars_beacons bcn Inner Join pp_risk_model_views.dw_ars_tls_stats tls 	On	         (bcn.src_ip=tls.src_ip 	And	       bcn.src_port=tls.src_port 	And	       bcn.dst_ip=tls.dst_ip 	and bcn.ux_time between tls.strt_time-60 and tls.strt_time+60) Where    bcn.cust_id = ? order by bcn.ux_ts desc
UPDATE PP_INTERIM.IMD_REPORTS_DEP_JOBS SET       job_total  = '1',       status     = 'Completed',       updated    = current_timestamp,       updated_by = 'pp_scheduler' WHERE       job_id = '2011061509231815492'
using user_id (varchar( 25 )) insert into unica_temp.UACEX1_535217_05(user_id) values ( :user_id );
INSERT INTO imk_scratch.gbase_item_3m_sample_google (item_id,upc_cd,brand,mpn) VALUES (?,?,?,?);
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_69212_223(USER_ID) values ( :USER_ID );
DATABASE "pp_stage"
using SELLER_ID (varchar( 25 )) insert into unica_temp.UACEX1_483078_jn(SELLER_ID) values ( :SELLER_ID );
INSERT INTO ad_working.DW_AD_RTM_OPTMZTN_SUM_W (smplng_start_dt,smplng_start_tm,rtm_msg_id,client_imprsn_cnt,srvr_imprsn_cnt,imprsn_clk_cnt,pause_cnt,resume_cnt,flr_cnt,expndbl_imprsn_cnt,expnd_cnt,clps_cnt,ext_graphic_ads_timeout_count) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);
SET QUERY_BAND = 'Table=dw_adptv_pmt_payreq_parameter; Script=dw_adptv_pmt_payreq_parameter_upd.sql;' FOR SESSION;
SELECT TableKind from DBC.TablesV WHERE DatabaseName='IM_T' AND TableName='DW_IMK_MPX_VT_EVENTS';
USING ("customer_id" CHAR (20))INSERT INTO pp_scratch_risk."prod_alh_today_swapcand_ten" ("customer_id") VALUES (:"customer_id")
HELP SESSION
select database
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   24718342991,   '2011061515145211902',   'tarun',   '--pp_discovery_views',   'dim_payment_flow',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   23790841676,   '2011061512264017025',   'acct_review_survey',   'pp_cs_access_views',   'dim_cs_org_dept',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
update dbcmngr.alertcontrol       set controldate=1110615, controltime=212401272       where id=20
using user_id (varchar( 25 )) insert into unica_temp.UACEX1_69199_qe3(user_id) values ( :user_id );
SELECT /* MacAttachmentTeraDataMap.FIND_ALL_BY_ACTIVITYIDS_IN.-2 .2*/ match.MAC_ATTACHMENT_ID, match.MAC_ACTIVITY_ID, match.ATTACHMENT_NAME, match.ATTACHMENT_PATH, match.EXPIRATION_DATE, match.CREATION_DATE, match.LAST_MODIFIED_DATE, match.MIME_TYPE FROM mac_attachment match WHERE MAC_ACTIVITY_ID IN (?, ?)
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_356716_8f1(USER_ID) values ( :USER_ID );
using SLR_ID (varchar( 25 )), ITEM_ID (varchar( 25 )), ATTR_ID_39 (varchar( 22 )), Veh_Make (varchar( 600 )), ATTR_ID_41 (varchar( 22 )), Veh_Model (varchar( 600 )), ATTR_ID_38 (varchar( 22 )), Stream_Flag (varchar( 10 )) insert into Unica_Temp.AC_US_Mtrs_005UJ_Trnsp(SLR_ID, ITEM_ID, ATTR_ID_39, Veh_Make, ATTR_ID_41, Veh_Model, ATTR_ID_38, Stream_Flag) values ( :SLR_ID, :ITEM_ID, :ATTR_ID_39, :Veh_Make, :ATTR_ID_41, :Veh_Model, :ATTR_ID_38, :Stream_Flag );
using user_id (varchar( 25 )) insert into unica_temp.UACEX1_69199_qe3(user_id) values ( :user_id );
HELP COLUMN "PP_UNICA"."UAC_143527_116".*
UPDATE PP_INTERIM.IMD_REPORTS_DEP_JOBS SET       job_total  = '1',       status     = 'Completed',       updated    = current_timestamp,       updated_by = 'pp_scheduler' WHERE       job_id = '2011061508151614689'
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_67048_gmd(USER_ID) values ( :USER_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   29347974989,   '2011061515145211902',   'tarun',   'pp_reporting_tables',   'ta_nps_sample_2011',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_463373_rj(USER_ID) values ( :USER_ID );
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_405527_sz4(USER_ID) values ( :USER_ID );
drop table ZZTOHC1UZ7MMD008
BT;
ET;
INSERT INTO pp_scratch_goraeu.dub_dw_log SELECT CAST(CURRENT_TIMESTAMP(2) AS TIMESTAMP(2)), 'GEN-BatModelCheckRunner-Daily.bat', SESSION, 2;
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   27901620999,   '2011061513133317491',   'random_cb_auto_close',   'pp_access_views',   'dw_atk_case_general',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_23923_gn4(USER_ID) values ( :USER_ID );
SET QUERY_BAND = 'SA=avaya;TGTDB=MIESA01;TGTTBL=d_wi_contact_reason;TBID=d_wi_contact_reason;SCRIPTNAME=dw_mi_esa01.d_wi_contact_reason.ups.sql;' FOR SESSION;
USING ("customer_id" CHAR (20),"added_date" DATE,"reason_code" FLOAT,"deposit_transid" FLOAT,"TRANSACTION_USD_EQUIV_AMT" FLOAT,"TXN_CREATED_UNIXTIME" FLOAT)INSERT INTO pp_scratch_risk."unauth_add_funds_test" ("customer_id","added_date","reason_code","deposit_transid","TRANSACTION_USD_EQUIV_AMT","TXN_CREATED_UNIXTIME") VALUES (:"customer_id",:"added_date",:"reason_code",:"deposit_transid",:"TRANSACTION_USD_EQUIV_AMT",:"TXN_CREATED_UNIXTIME")
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_454787_b43(USER_ID) values ( :USER_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   22335627798,   '2011061512264012448',   'daily_dd_smi_changes',   'pp_reporting_tables',   'kh_dailydd_tmp02',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
END LOADING;
SELECT /* MacAttachmentTeraDataMap.FIND_ALL_BY_ACTIVITYIDS_IN.-2 .25*/ match.MAC_ATTACHMENT_ID, match.MAC_ACTIVITY_ID, match.ATTACHMENT_NAME, match.ATTACHMENT_PATH, match.EXPIRATION_DATE, match.CREATION_DATE, match.LAST_MODIFIED_DATE, match.MIME_TYPE FROM mac_attachment match WHERE MAC_ACTIVITY_ID IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
COMMIT
INSERT INTO PP_SCRATCH.SSB_DFATLIST ( ? );
insert into gdw_tables.DW_DA_CHECKSUM_LOG (sys_name,sa_name,db_name,tbl_name,col_name,checksum_cnt,where_con) values (?,?,?,?,?,?,?) ;
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_24107_ea5(USER_ID) values ( :USER_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   28393802673,   '2011061513133317169',   'ms_pod_a_accounts',   'pp_reporting_tables',   'oma_fx_rid6312_003',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   28120006751,   '2011061515145211902',   'tarun',   '--pp_discovery_views',   'dim_payment_flow',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using user_id (varchar( 25 )) insert into unica_temp.UACEX1_467959_wc(user_id) values ( :user_id );
using SLR_ID (varchar( 25 )) insert into unica_temp.UACEX1_155633_cj9(SLR_ID) values ( :SLR_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   38193263022,   '2011061510193113978',   'masspay',   'pp_reporting_tables',   'jv_masspay_ps',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
USING ID(CHAR(22)), TIME_CREATED(CHAR(19)), CC_ID(CHAR(20)), CLIENT_ID(CHAR(4)), CC_TYPE(CHAR(1)), EBIT_ORDERID(CHAR(40)), ACCOUNT_NUMBER(CHAR(20)), CCTRANS_TYPE(CHAR(1)), TIME_PROCESSED(CHAR(19)), FLAGS(CHAR(11)), AMOUNT(CHAR(20)), USD_AMOUNT(CHAR(20)), STATUS(CHAR(1)), RESPONSE(CHAR(64)), AUTHORIZATION_CODE(CHAR(765)), MESSAGE(CHAR(765)), AVS_RESPONSE(CHAR(16)), AUTHORIZER(CHAR(1)), PARENTID(CHAR(22)), EBIT_RECOMMEND(CHAR(16)), EBIT_REPORT_ERR(CHAR(16)), EBIT_REASON(CHAR(255)), DECLINED_RESPONSE(CHAR(16)), VENDOR_TRANSID(CHAR(40)), CV_RESULT(CHAR(3)), CURRENCY_CODE(CHAR(3)), SOFT_DESCRIPTOR(CHAR(57)), USD_DISBURSEMENT(CHAR(20)), REFERENCE_NUMBER(CHAR(765)), MERCHANT_ID(CHAR(40)), CE_SELLER_STATE(CHAR(5)), ACQUIRER(CHAR(3)), RATE_CODE(CHAR(5)), AMEX_COMP_PLAN(CHAR(4)), TIME_ROW_UPDATED(CHAR(19)), FLAGS2(CHAR(11)), CARD_NETWORK(CHAR(2)), GG_TIMESTAMP(CHAR(19)), GG_ROW_ID(CHAR(20)), NEWLINECHAR(CHAR(1)) insert into pp_stage.stg_wcctrans_intra ( 	id, 	time_created, 	cc_id, 	client_id, 	cc_type, 	ebit_orderid, 	account_number, 	cctrans_type, 	time_processed, 	flags, 	amount, 	usd_amount, 	status, 	response, 	authorization_code, 	message, 	avs_response, 	authorizer, 	parentid, 	ebit_recommend, 	ebit_report_err, 	ebit_reason, 	declined_response, 	vendor_transid, 	cv_result, 	currency_code, 	soft_descriptor, 	usd_disbursement, 	reference_number, 	merchant_id, 	ce_seller_state, 	acquirer, 	rate_code, 	amex_comp_plan, 	time_row_updated, 	flags2, 	card_network, 	gg_timestamp, 	gg_row_id ) VALUES ( 	:id, 	:time_created, 	:cc_id, 	:client_id, 	:cc_type, 	:ebit_orderid, 	:account_number, 	:cctrans_type, 	:time_processed, 	:flags, 	:amount, 	:usd_amount, 	:status, 	:response, 	:authorization_code, 	:message, 	:avs_response, 	:authorizer, 	:parentid, 	:ebit_recommend, 	:ebit_report_err, 	:ebit_reason, 	:declined_response, 	:vendor_transid, 	:cv_result, 	:currency_code, 	:soft_descriptor, 	:usd_disbursement, 	:reference_number, 	:merchant_id, 	:ce_seller_state, 	:acquirer, 	:rate_code, 	:amex_comp_plan, 	:time_row_updated, 	:flags2, 	:card_network, 	:gg_timestamp, 	:gg_row_id ) ;
select database
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_413014_pp1(USER_ID) values ( :USER_ID );
BEGIN LOADING UUD_tables."BML_UPLD_APPR4" ERRORFILES UUD_tables."ET_BML_UPLD_APPR4", UUD_tables."UV_BML_UPLD_APPR4" CHECKPOINT 0 WITH INTERVAL;
RESTART DUMP "DC_TABLES"."DW_DC_RSPNS", CLUSTER = 73 151 229 307 385 463 541 619 697 775 853 931 1009 1087 1165 1243 1321 1399 1477 1555 ;
UPDATE DW_USER_URL SET CUSTOMER_ID = ? , URL_CREATED_TS = ? , URL_CREATED_DATE = ? , URL_FLAG1 = ? , URL = ? , SRC_ROW_UPDATE_TS = ? , CRE_USER = ? , CRE_DATE = ? , UPD_USER = ? , UPD_DATE = ? WHERE USER_URL_ID = ? ;
using SELLER_ID (varchar( 25 )) insert into unica_temp.UACEX1_483078_jn(SELLER_ID) values ( :SELLER_ID );
USING        _spVV1 (CHAR(30), CHARACTER SET LATIN, NOT CASESPECIFIC),       _spVV0 (CHAR(30), CHARACTER SET LATIN, NOT CASESPECIFIC),       _spVV3 (VARCHAR(1024), CHARACTER SET LATIN, NOT CASESPECIFIC)SELECT ((('grant '||:_spVV1 )||' to ')||(TRIM(BOTH  FROM :_spVV0 )))||';' INTO :_spVV3 ;
COLLECT STATISTICS pp_reporting_tables.abruntz_daily_exchange_rate  COLUMN FROM_CURRENCY
RESTART CHECKPOINT;
SET QUERY_BAND = 'Table=dw_cs_tbl_current; Script=dw_cs_tbl_current_ins.sql;' FOR SESSION;
using USER_ID_ID (varchar( 25 )), CampaignCode (varchar( 32 )), Current_dt (varchar( 10 )) insert into Unica_Tables.PAYPAL_PASTRECIPIENTS(USER_ID_ID, CampaignCode, Current_dt) values ( :USER_ID_ID, :CampaignCode, :Current_dt );
using USER_ID (varchar( 25 )), CMPGN_CODE (varchar( 32 )), DESCRIPTION (varchar( 1 )), CRE_DATE (varchar( 10 )) insert into Unica_Tables.AC_EXTD_CH_UK(USER_ID, CMPGN_CODE, DESCRIPTION, CRE_DATE) values ( :USER_ID, :CMPGN_CODE, :DESCRIPTION, :CRE_DATE );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   27491741199,   '2011061515145211902',   'tarun',   'pp_discovery_views',   'dim_calendar_month',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   33050813826,   '2011061510193118463',   'MRM_ACI_Client_feed',   'pp_access_views',   'dw_customer',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
del working.stg_cs_webform_contact_w;
BEGIN LOADING pp_unica.UA_0737_147940 ERRORFILES PP_UNICA.UA_0737_147940_err1, PP_UNICA.UA_0737_147940_err2 CHECKPOINT 100000 WITH INTERVAL;
using BYR_ID (varchar( 25 )) insert into unica_temp.UACEX1_575601_o4(BYR_ID) values ( :BYR_ID );
SELECT TableKind from DBC.TablesV WHERE DatabaseName='GDW_TABLES' AND TableName='DW_IMK_LSTG_FEED';
ET;
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_23722_jp7(USER_ID) values ( :USER_ID );
INSERT INTO stg_na_external_id_xref ( na_external_id_xref_id , network_id , external_id_name , external_id_value , creation_date , last_modified_date ) VALUES ( ? , ? , ? , ? , ? , ? ) ;
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   39730015089,   '2011061515145211902',   'tarun',   'pp_reporting_tables',   'ta_nps_cust_var_2011',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
insert into pp_scratch_risk.fso_NODROP_pattern (fso) values(772233012);
BT;
USING        _spVV2 (CHAR(30), CHARACTER SET LATIN, NOT CASESPECIFIC),       _spVV0 (CHAR(30), CHARACTER SET LATIN, NOT CASESPECIFIC),       _spVV1 (VARCHAR(2047), CHARACTER SET LATIN, NOT CASESPECIFIC),       _spVV4 (VARCHAR(2176), CHARACTER SET LATIN, NOT CASESPECIFIC)SELECT ((((('collect statistics on '||(TRIM(BOTH  FROM :_spVV2 )))||'.')||(TRIM(BOTH  FROM :_spVV0 )))||' column( ')||(TRIM(BOTH  FROM :_spVV1 )))||');' INTO :_spVV4 ;
using SELLER_ID (varchar( 25 )) insert into unica_temp.UACEX1_483078_in(SELLER_ID) values ( :SELLER_ID );
USING ("model" CHAR (25),"above_score_cutoff" INTEGER,"scoredate" DATE,"incl" INTEGER,"DropOut" INTEGER,"AddIn" INTEGER,"s_hold_flag" INTEGER,"test" INTEGER,"customer_id" CHAR (19))INSERT INTO pp_tables_risk."prod_alh_de_tc" ("model","above_score_cutoff","scoredate","incl","DropOut","AddIn","s_hold_flag","test","customer_id") VALUES (:"model",:"above_score_cutoff",:"scoredate",:"incl",:"DropOut",:"AddIn",:"s_hold_flag",:"test",:"customer_id")
ET
SELECT NULL(VARCHAR(90) ),DATABASENAME(VARCHAR(90) ),TRIM(TABLENAME(VARCHAR(90) )),CASE WHEN DATABASENAME <> 'DBC' THEN CASE TABLEKIND WHEN 'T' THEN 'TABLE' WHEN 'O' THEN 'TABLE' WHEN 'V' THEN 'VIEW' WHEN 'M' THEN 'MACRO' WHEN 'J' THEN 'JOURNAL' WHEN 'I' THEN 'JOIN INDEX' WHEN 'U' THEN 'TYPE' ELSE '' END ELSE CASE TABLEKIND WHEN 'T' THEN 'SYSTEM TABLE' WHEN 'O' THEN 'SYSTEM TABLE' WHEN 'V' THEN 'SYSTEM TABLE' WHEN 'M' THEN 'SYSTEM MACRO' WHEN 'J' THEN 'SYSTEM JOURN' WHEN 'I' THEN 'SYSTEM JINDX' WHEN 'U' THEN 'TYPE' ELSE '' END END (NAMED TABLE_TYPE),COMMENTSTRING(VARCHAR(254),NAMED REMARKS) FROM DBC.TABLES  WHERE UPPER(DATABASENAME) = UPPER(TRIM('working')) AND UPPER(TRIM(TABLENAME)) LIKE UPPER(TRIM('stg\_odr\_pp\_clm\_snad\_rtrn\_w')) ESCAPE '\' AND  UPPER(TABLEKIND) IN ('T', 'O', 'V', 'U') ORDER BY 4,1,2,3
DROP TABLE ZZTUSLQTP5GSP000
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   27871537707,   '2011061512264019065',   'oma_r7425.tdw.sql',   'pp_reporting_tables',   'oma_r7425_tmp8',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_405527_nz4(USER_ID) values ( :USER_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   26493671547,   '2011061513133516602',   'csat_frnt_office_srv',   'pp_reporting_tables',   'satmetrix_fo_tmp1',   'N',   'N',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_488940_232(USER_ID) values ( :USER_ID );
USING ("customer_id" CHAR (20),"added_date" DATE,"reason_code" FLOAT,"deposit_transid" FLOAT,"TRANSACTION_USD_EQUIV_AMT" FLOAT,"TXN_CREATED_UNIXTIME" FLOAT)INSERT INTO pp_scratch_risk."unauth_add_funds_test" ("customer_id","added_date","reason_code","deposit_transid","TRANSACTION_USD_EQUIV_AMT","TXN_CREATED_UNIXTIME") VALUES (:"customer_id",:"added_date",:"reason_code",:"deposit_transid",:"TRANSACTION_USD_EQUIV_AMT",:"TXN_CREATED_UNIXTIME")
SELECT INFOKEY, INFODATA FROM DBC.DBCINFOV ORDER BY 1;
INSERT INTO PP_UNICA.QA_SAMPLE_349639 ( CustomerNumber_ID , CellName ) VALUES ( ? , ? ) ;
using user_id (varchar( 25 )) insert into unica_temp.UACEX1_69199_se3(user_id) values ( :user_id );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   38649623296,   '2011061515145211902',   'tarun',   'pp_reporting_tables',   'ta_nps_metrics_2011',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
CHECKPOINT LOADING;
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   29676131845,   '2011061511171119436',   'IFTI_Compliance',   'pp_reporting_tables',   'abruntz_IFTI',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
using SELLER_ID (varchar( 25 )) insert into unica_temp.UACEX1_483078_gn(SELLER_ID) values ( :SELLER_ID );
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_79202_bf6(USER_ID) values ( :USER_ID );
CREATE VOLATILE TABLE ta_us, no log, no fallback as  ( SELECT 	 MAX (cust_Id) cust_id 	,agg.cust_busn_seg_key 	,comp_cntry_busn_seg_key 	,cust_acct_clsfn_key 	,sf_acct_id  	,ntpv_12_mth_recv_usd_amt 	,recv_actvty_type_key  	,success_12_mth_recv_cnt  	,cntry_code 	,engseg.cust_busn_seg_name 	,mth_id 	,RANK () OVER (PARTITION BY cntry_code,sf_acct_id ORDER BY ntpv_12_mth_recv_usd_amt DESC) rank_tpv FROM 	pp_discovery_views.agg_cust_profile_mth agg JOIN  	(SELECT cust_busn_seg_key 			    ,cust_busn_seg_name  		FROM  		pp_discovery_views.dim_cust_busn_seg  		WHERE  		cust_busn_seg_name IN ('Very LOW Volume','LOW Volume','HIGH Volume','NEW','MEDIUM Volume') 	) engseg ON  	agg.comp_cntry_busn_seg_key = engseg.cust_busn_seg_key		-- company country level segment key WHERE  	agg.mth_id =  (SELECT mth_id FROM pp_discovery_views.dim_calendar_month WHERE mth_offset = -1) 	AND cust_acct_clsfn_key = 2 	AND cntry_code IN ('US','GB','IE','DE','CA','AU','NZ') 	AND recv_actvty_type_key = 1 	AND sf_acct_id <> '0' 	QUALIFY rank_tpv = 1 GROUP BY 2,3,4,5,6,7,8,9,10,11 )  WITH DATA  UNIQUE PRIMARY INDEX (cust_id) ON COMMIT PRESERVE ROWS
using USER_ID (varchar( 25 )) insert into unica_temp.UACEX1_405527_sz4(USER_ID) values ( :USER_ID );
INSERT INTO PP_INTERIM.IMD_REPORTS_JOBS_SQL_TABLES (   report_sql_id,   report_run_id,   report_id,   table_db,   table_name,   table_process,   status,   created,   created_by,   updated,   updated_by ) VALUES (   22345742771,   '2011061513133510674',   'MSS037S_AMOTPerforma',   'pp_cs_access_views',   'fact_cs_workitem_seg',   'N',   'S',   current_timestamp,   'pp_adm',   current_timestamp,   'pp_adm' )
del working.stg_kwdm_grph_dbuy_cost_w;
RESTART CHECKPOINT;
SET QUERY_BAND = 'DEV_CAMPAIGNCODE=000040233;' FOR SESSION;
